"""empty message

Revision ID: 0cd08cbdbd89
Revises: 
Create Date: 2018-12-16 16:05:36.680028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd08cbdbd89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=True),
    sa.Column('upwd', sa.String(length=100), nullable=True),
    sa.Column('uemail', sa.String(length=100), nullable=True),
    sa.Column('uphone', sa.String(length=11), nullable=True),
    sa.Column('uface', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uemail'),
    sa.UniqueConstraint('uphone')
    )
    op.create_index(op.f('ix_user_addtime'), 'user', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_addtime'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
