"""empty message

Revision ID: 243c5f2b80a5
Revises: 3a011332258e
Create Date: 2019-01-20 16:05:32.525411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243c5f2b80a5'
down_revision = '3a011332258e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    # ### end Alembic commands ###
