"""empty message

Revision ID: 2e3685ff2af9
Revises: e4fdf6777aa8
Create Date: 2019-01-02 20:45:10.103274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3685ff2af9'
down_revision = 'e4fdf6777aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('cover', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'travels', ['cover'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'travels', type_='unique')
    op.drop_column('travels', 'cover')
    # ### end Alembic commands ###
