"""empty message

Revision ID: 349ce9683de1
Revises: 6f3590e5e7a2
Create Date: 2018-12-28 20:59:00.079941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349ce9683de1'
down_revision = '6f3590e5e7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('areaName', sa.String(length=100), nullable=True),
    sa.Column('is_recommend', sa.Boolean(), nullable=True),
    sa.Column('introduce', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_addtime'), 'area', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_area_addtime'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
