"""empty message

Revision ID: 3a011332258e
Revises: b05f938bde77
Create Date: 2019-01-20 15:42:48.844684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a011332258e'
down_revision = 'b05f938bde77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('send_id', sa.Integer(), nullable=True),
    sa.Column('isalive', sa.Boolean(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_addtime'), 'message', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_addtime'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
