"""empty message

Revision ID: 3f71d4efd2dc
Revises: dece913160eb
Create Date: 2019-01-06 16:50:54.063815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f71d4efd2dc'
down_revision = 'dece913160eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cover', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('introduce', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'introduce')
    op.drop_column('user', 'cover')
    # ### end Alembic commands ###
