"""empty message

Revision ID: 459c03086384
Revises: b40decd29189
Create Date: 2019-01-06 17:14:08.142604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459c03086384'
down_revision = 'b40decd29189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'travels', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'travels', type_='foreignkey')
    op.drop_column('travels', 'author_id')
    # ### end Alembic commands ###
