"""empty message

Revision ID: 61fcdf3fad48
Revises: 3f71d4efd2dc
Create Date: 2019-01-06 17:02:15.663066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fcdf3fad48'
down_revision = '3f71d4efd2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'travels', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'travels', type_='foreignkey')
    op.drop_column('travels', 'user_id')
    # ### end Alembic commands ###
