"""empty message

Revision ID: 8001ba9318b6
Revises: 349ce9683de1
Create Date: 2018-12-30 11:36:00.963408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8001ba9318b6'
down_revision = '349ce9683de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=True),
    sa.Column('uemail', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_addtime'), 'suggestion', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_addtime'), table_name='suggestion')
    op.drop_table('suggestion')
    # ### end Alembic commands ###
