"""empty message

Revision ID: 9cce0898d696
Revises: 2e3685ff2af9
Create Date: 2019-01-03 17:23:52.999632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cce0898d696'
down_revision = '2e3685ff2af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('is_recommend', sa.Boolean(), nullable=True))
    op.add_column('travels', sa.Column('isactive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travels', 'isactive')
    op.drop_column('travels', 'is_recommend')
    # ### end Alembic commands ###
