"""empty message

Revision ID: b05f938bde77
Revises: ad34a1f59122
Create Date: 2019-01-19 11:36:08.309906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05f938bde77'
down_revision = 'ad34a1f59122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focused_id', sa.Integer(), nullable=True),
    sa.Column('focuser_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_addtime'), 'friends', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friends_addtime'), table_name='friends')
    op.drop_table('friends')
    # ### end Alembic commands ###
