"""empty message

Revision ID: b40decd29189
Revises: 61fcdf3fad48
Create Date: 2019-01-06 17:06:52.836376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b40decd29189'
down_revision = '61fcdf3fad48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('travels_ibfk_2', 'travels', type_='foreignkey')
    op.drop_column('travels', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('travels_ibfk_2', 'travels', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
