"""empty message

Revision ID: b724e7844c7a
Revises: 
Create Date: 2018-12-31 13:27:10.489507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b724e7844c7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=True),
    sa.Column('upwd', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uname')
    )
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('areaName', sa.String(length=100), nullable=True),
    sa.Column('is_recommend', sa.Boolean(), nullable=True),
    sa.Column('introduce', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_addtime'), 'area', ['addtime'], unique=False)
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=True),
    sa.Column('uemail', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_addtime'), 'suggestion', ['addtime'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=True),
    sa.Column('upwd', sa.String(length=100), nullable=True),
    sa.Column('uemail', sa.String(length=100), nullable=True),
    sa.Column('uphone', sa.String(length=11), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uemail'),
    sa.UniqueConstraint('uname'),
    sa.UniqueConstraint('uphone')
    )
    op.create_index(op.f('ix_user_addtime'), 'user', ['addtime'], unique=False)
    op.create_table('adminlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['adminlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminlog_addtime'), 'adminlog', ['addtime'], unique=False)
    op.create_table('operlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=600), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['adminlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operlog_addtime'), 'operlog', ['addtime'], unique=False)
    op.create_table('scenic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenicname', sa.String(length=255), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('introduce', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_recommend', sa.Boolean(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cover'),
    sa.UniqueConstraint('scenicname')
    )
    op.create_index(op.f('ix_scenic_addtime'), 'scenic', ['addtime'], unique=False)
    op.create_table('userlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userlog_addtime'), 'userlog', ['addtime'], unique=False)
    op.create_table('sceniccollect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scenic_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sceniccollect_addtime'), 'sceniccollect', ['addtime'], unique=False)
    op.create_table('travels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('scenic_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travels_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travels_id'], ['travels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_addtime'), 'review', ['addtime'], unique=False)
    op.create_table('travelscollect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('travels_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travels_id'], ['travels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travelscollect_addtime'), 'travelscollect', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travelscollect_addtime'), table_name='travelscollect')
    op.drop_table('travelscollect')
    op.drop_index(op.f('ix_review_addtime'), table_name='review')
    op.drop_table('review')
    op.drop_table('travels')
    op.drop_index(op.f('ix_sceniccollect_addtime'), table_name='sceniccollect')
    op.drop_table('sceniccollect')
    op.drop_index(op.f('ix_userlog_addtime'), table_name='userlog')
    op.drop_table('userlog')
    op.drop_index(op.f('ix_scenic_addtime'), table_name='scenic')
    op.drop_table('scenic')
    op.drop_index(op.f('ix_operlog_addtime'), table_name='operlog')
    op.drop_table('operlog')
    op.drop_index(op.f('ix_adminlog_addtime'), table_name='adminlog')
    op.drop_table('adminlog')
    op.drop_index(op.f('ix_user_addtime'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_suggestion_addtime'), table_name='suggestion')
    op.drop_table('suggestion')
    op.drop_index(op.f('ix_area_addtime'), table_name='area')
    op.drop_table('area')
    op.drop_table('adminlist')
    # ### end Alembic commands ###
