"""empty message

Revision ID: d188a6b18c98
Revises: aa73c937f4b4
Create Date: 2018-12-25 09:04:14.768161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd188a6b18c98'
down_revision = 'aa73c937f4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userlog_ibfk_2', 'userlog', type_='foreignkey')
    op.drop_column('userlog', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userlog', sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key('userlog_ibfk_2', 'userlog', 'user', ['user_name'], ['uname'])
    # ### end Alembic commands ###
