"""empty message

Revision ID: e970715e7989
Revises: 459c03086384
Create Date: 2019-01-06 17:31:40.366466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e970715e7989'
down_revision = '459c03086384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travels', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
